image: node:alpine

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm run lint
          - npm run build-prod
    - step:
        script:
          - docker build -t development/ui:0.0.1 .
          - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          - docker push us.gcr.io/development/ui:0.0.1

options:
  docker: true
